language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

install: 
- npm install
script: 
- npm  run test
branches:
  only:
    - development
   services:
 - postgresql
before_script:
  - psql -c "CREATE DATABASE teamwork.sql;" -U postgres

    after_success: 
    - npm coverage